---
version: '3'
services:
  google-calendar-interface:
    build: "./google-calendar-interface"
    environment:
      - GOOGLE_SERVICE_ACCOUNT_EMAIL
      - GOOGLE_SERVICE_ACCOUNT_KEY
  embot-core:
    build: "./embot-core"
    environment:
      - CALENDAR_INTERFACE_URL=http://google-calendar-interface:3000
      - JIRA_BASE_URL=https://spindance.atlassian.net
      - JIRA_USERNAME=jiraApps
      - JIRA_PASSWORD
  chat-interface:
    build: "./chat-interface"
    environment:
      - HANGOUTS_SECRET_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
      - LEX_BOT_VERSION=latest
      - CORE_URL=http://embot-core:3000
    ports:
      - "3000:3000"
  slack-interface:
    build: "./slack-interface"
    environment:
      - SLACK_API_TOKEN
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - AWS_PROFILE
      - LEX_BOT_VERSION=latest
      - CORE_URL=http://embot-core:3000
