---
version: '3'
services:
  embot-core:
    build: "./embot-core"
  chat-lex-interface:
    build: "./chat-lex-interface"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - CORE_URL=http://embot-core:3000
      - HANGOUTS_SECRET_TOKEN
    ports:
      - "3000:3000"
