---
version: '3'
services:
  google-calendar-interface:
    build: "./google-calendar-interface"
    environment:
      - GOOGLE_SERVICE_ACCOUNT_EMAIL
      - GOOGLE_SERVICE_ACCOUNT_KEY
  embot-core:
    build: "./embot-core"
    environment:
      - CALENDAR_INTERFACE_URL=http://google-calendar-interface:3000
  chat-interface:
    build: "./chat-interface"
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - CORE_URL=http://embot-core:3000
      - HANGOUTS_SECRET_TOKEN
      - LEX_BOT_VERSION=latest
    ports:
      - "3000:3000"
